### ISSUE TITLE
needs change

### ISSUE THREAD

**Issue by davidhq** [Anyass3/hyp-files-app#1]
https://github.com/Anyass3/hyp-files-app/blob/5464476eb32f80b3046c6d89a2643f8aabf0da02/backend/server.ts#L119-L121

should be 
```js

const channelList = acceptor.registerProtocol({
		protocol: 'dmtapp/hyp',
		onConnect: async ({ channel }) => onConnect({ channel: enhanceChannel(channel) })
```

there are no lanes anymore... protocol should be unique in regard to dmt-proc and all frontends connecting to it... so for now it's ok like this `'dmtapp/hyp'` since nobody else is going to use this

**Comment by Anyass3** [comment]
checkout this commit in dev branch https://github.com/Anyass3/hyp-files-app/commit/a4442e96ec0ed848d9c01036d187a16066e4edd4
